import Head from "next/head";
import Articles from "../components/Articles";
import Hero from "../components/Hero";
import Socials from "../components/Socials";
import Staff from "../components/Staff";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>گروه وکلای صدرا</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sadra.png" />
      </Head>
      <Hero />
      <Socials />
      <Articles />
      <Staff />
      <Footer />
    </div>
  );
}
